name: CI - iOS
run-name: Run by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  testing_job:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: "1.9.0"

      - name: Run Tests
        run: |
          cd TestSample  # Position yourself inside the TestSample directory
          xcodebuild -workspace TestSample.xcworkspace \
               -scheme TestSample \
               -sdk iphonesimulator \
               -destination 'platform=iOS Simulator,name=iPhone 12' \
               test
